//
//  EpisodeDetailsViperPresenter.swift
//  TVShows
//
//  Created by Infinum on 06/08/2019.
//  Copyright (c) 2019 Infinum Academy. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxCocoa
import RxSwift

final class EpisodeDetailsViperPresenter {

    // MARK: - Private properties -

    private unowned let view: EpisodeDetailsViperViewInterface
    private let interactor: EpisodeDetailsViperInteractorInterface
    private let wireframe: EpisodeDetailsViperWireframeInterface
    private let disposeBag = DisposeBag()
    
    // MARK: - Lifecycle -

    init(view: EpisodeDetailsViperViewInterface, interactor: EpisodeDetailsViperInteractorInterface, wireframe: EpisodeDetailsViperWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension EpisodeDetailsViperPresenter: EpisodeDetailsViperPresenterInterface {
    func configure() {
        wireframe.showLoading()
        view.showEpisodeDetails()
        wireframe.hideLoading()
    }
    
}
