//
//  EpisodeDetailsViperInterfaces.swift
//  TVShows
//
//  Created by Infinum on 06/08/2019.
//  Copyright (c) 2019 Infinum Academy. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
//this is such an overkill for gods sake
protocol EpisodeDetailsViperWireframeInterface: WireframeInterface {
    func toComments()
    func back()
    func showLoading()
    func hideLoading()
    func show(error: Error)
}

protocol EpisodeDetailsViperViewInterface: ViewInterface {
    func showEpisodeDetails()
}

protocol EpisodeDetailsViperPresenterInterface: PresenterInterface {
    func configure()
}

protocol EpisodeDetailsViperInteractorInterface: InteractorInterface {
}
