//
//  EpisodeDetailsViperInteractor.swift
//  TVShows
//
//  Created by Infinum on 06/08/2019.
//  Copyright (c) 2019 Infinum Academy. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class EpisodeDetailsViperInteractor {
}

// MARK: - Extensions -

extension EpisodeDetailsViperInteractor: EpisodeDetailsViperInteractorInterface {
}
