//
//  EpisodeDetailsViperViewController.swift
//  TVShows
//
//  Created by Infinum on 06/08/2019.
//  Copyright (c) 2019 Infinum Academy. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class EpisodeDetailsViperViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: EpisodeDetailsViperPresenterInterface!
    var episode: Episode? //wrong but i'm not sure how or what or why
    var showImageUrl: String = ""
    
    // MARK: - Outlets -
    
    @IBOutlet private weak var episodeTitleLabel: UILabel!
    @IBOutlet private weak var seasonEpisodeIndicatorLabel: UILabel!
    @IBOutlet private weak var descriptionLabel: UILabel!
    @IBOutlet private weak var episodeImage: UIImageView!
    @IBOutlet weak var backButton: UIButton!
    @IBOutlet weak var commentsButton: UIButton!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension EpisodeDetailsViperViewController: EpisodeDetailsViperViewInterface {
   
    func showEpisodeDetails() {
        guard let episode = episode else {
            showAlert(title: "Error", message: "Episode details are missing")
            return
        }
        
        descriptionLabel.text = episode.description
        episodeTitleLabel.text = episode.title
        seasonEpisodeIndicatorLabel.text = "S\(episode.season) E\(episode.episodeNumber)"
        
        if !episode.imageUrl.isEmpty {
            let url = URL(string: "https://api.infinum.academy" + episode.imageUrl)
            episodeImage.kf.setImage(with: url)
        }
        else if !showImageUrl.isEmpty {
            let url = URL(string: showImageUrl)
            episodeImage.kf.setImage(with: url)
        }
        else {
            episodeImage.image = UIImage(named: "ic-placeholder")
        }

    }
    
}
